server:
  port: 8788
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  client:
    config:
      default:
         connect-timeout: 5000
         read-timeout: 5000
    